# Generated by Django 3.2.5 on 2022-03-12 10:43

from django.db import migrations


def generate_profiles(apps, schema_editor):
    """
    Generate a profile for every user in the database.
    """
    ...


def add_profiles_to_checklists(apps, schema_editor):
    """
    Add owner's profile to every checklist in the database.
    """
    ...


class Migration(migrations.Migration):
    """
    Profile system
    1. Generate a profile for every user, with 'password' authentication.
    2. Add a profile to every checklist.
    """

    dependencies = [
        ('remember', '0008_checklist_profile'),
    ]

    operations = [
    ]
