# Generated by Django 3.2.5 on 2022-03-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0006_auto_20220312_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remember.profile'),
        ),
    ]
