# Generated by Django 3.2.5 on 2022-03-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0009_token_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='owner',
            new_name='owner_old',
        ),
    ]
