# Generated by Django 3.2.5 on 2022-03-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remember', '0010_rename_owner_checklist_owner_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='owner_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
