# Generated by Django 3.2.5 on 2022-03-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0011_alter_checklist_owner_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='profile',
            new_name='owner',
        ),
    ]
