# Generated by Django 3.2.5 on 2022-03-13 21:05

from django.db import migrations, models
import django.db.models.deletion


def records_logged_by(apps, schema_editor):
    """
    Mark records as logged by the checklist's owner.
    """
    db_alias = schema_editor.connection.alias
    Record = apps.get_model('remember', 'Record')
    for record in Record.objects.using(db_alias).all():
        record.logged_by = record.chore.list.owner


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0012_rename_profile_checklist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_lists', to='remember.Profile'),
        ),
        migrations.AddField(
            model_name='record',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remember.profile'),
        ),
        migrations.RunPython(records_logged_by),
    ]
